# Generated by Django 3.1.4 on 2020-12-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simID', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=47)),
                ('desc', models.TextField()),
                ('score', models.IntegerField(default=50)),
                ('correctDiag', models.BooleanField(default=False)),
            ],
        ),
    ]
